import { InputsForm as InputsFormType } from 'types/interfaces/FormTypes/InputsForm'
import { FieldValues, SubmitHandler, useFormContext } from 'react-hook-form'
import { InputObject } from 'types/interfaces/FormTypes/InputObject'

export interface FormProps {
  form: InputsFormType
  isAutoGenerated?: boolean
  submitCount?: number
  noScroll?: boolean
  onSubmit: SubmitHandler<FieldValues>
  onEnable?: () => void
  withAccordion?: boolean
  description?: string
  selectInputDependedValue?: number
  dependedInputObject?: InputObject
  formInformation?: string
}
