import {
  ACCESS_CARD_FOR_HIMSELF_CREDENTIALS_FORM,
  FORMATION_USER,
} from 'features/Auth/InscriptionForm/InscriptionFormsConstants/InscriptionForms.constants'
import { StepsRecord } from 'pages/SignupPage/SignupPage.type'
import GenericForm, { formTypes } from 'types/interfaces/FormTypes/GenericForm'
import { InterrogativeType } from 'types/interfaces/FormTypes/InterrogativeForm'
import { SignupAttributes } from 'types/models/AccessCard/SignupAttributes/SignupAttributes'
import { booleanToInterrogative } from 'utils/helpers/interrogative.helpers'
export const YES_LABEL = 'signup.yes'
export const NO_LABEL = 'signup.no'
export const INPUTS_INSCRIPTION_FORM = (
  stepsRecord: StepsRecord
): GenericForm<unknown, unknown, unknown>[] => {
  return [
    {
      id: 1,
      order: 1,
      name: SignupAttributes.IS_OVER_18,
      type: formTypes.INTERROGATIVE,
      text: 'signup.grater_18',

      value: booleanToInterrogative(stepsRecord.isOver18),
      options: [
        { value: InterrogativeType.YES, label: YES_LABEL },
        { value: InterrogativeType.NO, label: NO_LABEL },
      ],
      validate: (value: unknown) => (value as InterrogativeType[]).length > 0,
    },
    {
      id: 2,
      order: 2,
      name: SignupAttributes.CREDENTIALS,
      value: null,
      type: formTypes.INPUTS,
      text: 'signup.street',
      isNotValid: true,
      isRequired: true,
      isAutoGenerated: false,
      dependsOn: {
        id: 1,
        value: InterrogativeType.YES,
      },

      inputs: ACCESS_CARD_FOR_HIMSELF_CREDENTIALS_FORM(stepsRecord),
    },
    {
      id: 3,
      order: 2,
      name: SignupAttributes.EMAIL_ADDRESS,
      value: null,
      type: formTypes.INPUTS,
      text: 'signup.email_label',
      description: 'accessCard.email_label',

      dependsOn: {
        id: 1,
        value: InterrogativeType.NO,
      },
      inputs: FORMATION_USER(stepsRecord),
    },
  ]
}
