import {
  ACCESS_CARD_FOR_HIMSELF_CREDENTIALS_FORM,
  FORMATION_USER,
} from 'features/Auth/InscriptionForm/InscriptionFormsConstants/InscriptionForms.constants'
import { StepsRecord } from 'pages/SignupPage/SignupPage.type'
import GenericForm, { formTypes } from 'types/interfaces/FormTypes/GenericForm'
import { InputTypes } from 'types/interfaces/FormTypes/InputObject'
import { InterrogativeType } from 'types/interfaces/FormTypes/InterrogativeForm'
import { SignupAttributes } from 'types/models/AccessCard/SignupAttributes/SignupAttributes'
import { booleanToInterrogative } from 'utils/helpers/interrogative.helpers'

const YES_LABEL = 'yes'
const NO_LABEL = 'no'
export const INPUTS_INSCRIPTION_FORM = (
  stepsRecord: StepsRecord
): GenericForm<unknown, unknown, unknown>[] => {
  return [
    {
      id: 1,
      order: 1,
      name: SignupAttributes.CREDENTIALS,
      value: null,
      type: formTypes.INPUTS,
      text: 'accessCard.credentials',
      isNotValid: true,
      isRequired: true,
      isAutoGenerated: false,

      inputs: ACCESS_CARD_FOR_HIMSELF_CREDENTIALS_FORM(stepsRecord),
    },
    {
      id: 2,
      order: 2,
      name: SignupAttributes.IS_OVER_18,
      value: booleanToInterrogative(stepsRecord.isOver18),
      type: formTypes.INTERROGATIVE,
      text: 'accessCard.isHimself_question',
      description: 'accessCard.isHimself_description',
      options: [
        { label: YES_LABEL, value: InterrogativeType.YES },
        { label: NO_LABEL, value: InterrogativeType.NO },
      ],
      dependsOn: {
        id: 1,
        value: 'maison',
      },
      inputs: FORMATION_USER(stepsRecord),
    },

    {
      id: 3,
      order: 2,
      name: SignupAttributes.IS_OVER_18,
      value: booleanToInterrogative(stepsRecord.isOver18),
      type: formTypes.INTERROGATIVE,
      text: 'accessCard.isOver18_question',
      description: 'accessCard.isOver18_description',
      options: [
        { label: YES_LABEL, value: InterrogativeType.YES },
        { label: NO_LABEL, value: InterrogativeType.NO },
      ],
      dependsOn: {
        id: 1,
        value: InterrogativeType.NO,
      },
    },
    {
      id: 4,
      order: 3,
      name: SignupAttributes.HAVE_ID_CARD,
      value: booleanToInterrogative(stepsRecord.haveIdCard),
      type: formTypes.INTERROGATIVE,
      text: 'accessCard.haveIdCard_question',
      description: 'accessCard.haveIdCard_description',
      options: [
        { label: YES_LABEL, value: InterrogativeType.YES },
        { label: NO_LABEL, value: InterrogativeType.NO },
      ],
      dependsOn: {
        id: 3,
        value: InterrogativeType.NO,
      },
    },
  ]
}
