import { ReactNode } from 'react'
import { AlertObject } from 'types/interfaces/AlertObject'
import GenericForm from 'types/interfaces/FormTypes/GenericForm'

export interface GenericFormProps {
  form: GenericForm<unknown, unknown, unknown>
  isNotActive?: boolean
  alert?: AlertObject
  submitCount?: number
  isAutoGenerated?: boolean
  noScroll?: boolean
  isLoading?: boolean
  isError?: boolean
  withAccordion?: boolean
  additionalFileDescription?: ReactNode
  onChange: (value: unknown, arrayIndex?: number) => void
  onSubmit?: (values: Record<string, unknown>) => void
  onEnable?: () => void
  onValidateForm?: (isValid: boolean, formIndex?: number) => void
}
