import FilesForm from 'components/Forms/FilesForm/FilesForm'
import { GenericFormProps } from 'components/Forms/GenericForm/GenericForm.type'
import InputsForm from 'components/Forms/GenericForm/InputsForm/InputsForm'
import InterrogativeQuestion from 'components/Forms/InterrogativeQuestion/InterrogativeQuestion'
import { FilesForm as FilesFormType } from 'types/interfaces/FormTypes/FilesForm'
import { formTypes } from 'types/interfaces/FormTypes/GenericForm'
import { InputsForm as InputsFormType } from 'types/interfaces/FormTypes/InputsForm'
import { InterrogativeForm } from 'types/interfaces/FormTypes/InterrogativeForm'

function GenericForm({
  form,
  isNotActive,
  noScroll,
  alert,
  submitCount,
  isAutoGenerated,
  isLoading,
  isError,
  withAccordion,
  additionalFileDescription,
  onChange,
  onSubmit,
  onEnable,
  onValidateForm,
}: Readonly<GenericFormProps>) {
  if (isNotActive) return null
  switch (form.type) {
    case formTypes.INTERROGATIVE: {
      return (
        <InterrogativeQuestion
          onSelect={(value: string) => onChange(value)}
          {...(form as InterrogativeForm)}
          alert={alert}
        />
      )
    }
    case formTypes.INPUTS: {
      const inputsForm = form as InputsFormType
      return (
        <InputsForm
          form={inputsForm}
          onSubmit={(values: Record<string, unknown>) =>
            onSubmit && onSubmit(values)
          }
          onEnable={onEnable}
          isAutoGenerated={isAutoGenerated}
          submitCount={submitCount}
          noScroll={noScroll}
          withAccordion={withAccordion}
          description={inputsForm.description}
          selectInputDependedValue={inputsForm.selectedInputDependedValue}
          dependedInputObject={inputsForm.dependedInputObject}
          formInformation={inputsForm.formInformation}
        />
      )
    }
    case formTypes.FILES_UPLOAD: {
      const filesForm = form as FilesFormType
      return (
        <>
          {additionalFileDescription && additionalFileDescription}
          <FilesForm
            inputName={filesForm.name}
            files={filesForm.value}
            labels={filesForm.options}
            message={filesForm.text}
            onChange={onChange}
            filesMaxSize={filesForm.config?.maxSize}
            filesTypes={filesForm.config?.accept}
            maxFilesCount={filesForm.maxFiles ?? 3}
            hideFileDescription={filesForm.hideFilesDescriptions}
          />
        </>
      )
    }
  }
}
export default GenericForm
